In [1]:
import pandas as pd
import numpy as np


In [14]:
test = np.random.randint(5, size=(2,3,3,2))
test

array([[[[0, 1],
         [2, 3],
         [3, 4]],

        [[1, 4],
         [1, 2],
         [2, 0]],

        [[1, 3],
         [2, 0],
         [0, 1]]],


       [[[1, 4],
         [1, 3],
         [4, 3]],

        [[3, 2],
         [2, 3],
         [4, 3]],

        [[0, 0],
         [3, 2],
         [4, 4]]]])

In [15]:
test[0][0][0][:1]

array([0])

In [16]:
test[:1][0][0][0]

array([0, 1])

In [17]:
test[0][0][0][0]

0